rtx.di.enableRayTracedBiasCorrection = True
rtx.graphicsPreset = 0
rtx.di.stealBoundaryPixelSamplesWhenOutsideOfScreen = True
rtx.dlssPreset = 2
rtx.qualityDLSS = 3
rtx.dlfg.maxInterpolatedFrames = 1
rtx.di.initialSampleCount = 32
rtx.defaultToAdvancedUI = True
rtx.denoiseDirectAndIndirectLightingSeparately = True
rtx.di.enableDenoiserConfidence = True
rtx.di.permutationSamplingNthFrame = 1
rtx.di.enableBestLightSampling = True
rtx.di.spatialSamples = 4
rtx.neeCache.enable = True
rtx.frameGenerationType = 1
rtx.reflexMode = 2
rtx.di.enableSampleStealing = True
